<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ItemMasterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Clear the table first
        DB::table('itemmaster')->truncate();

        $items = [
            [
                'fInAct' => false,
                'ItmCd' => 'ITM001',
                'Status' => 'Active',
                'CKey' => 1, // Assuming this references code_master
                'ItemCode' => 'P001',
                'BarCode' => '8901234567890',
                'ItmNm' => 'Premium Rice 5kg',
                'EnglishName' => 'Premium Rice 5kg',
                'catkey' => 'CAT001', // Assuming this references code_master
                'ItmRefKy' => null,
                'UnitKy' => 1, // Assuming unit reference
                'CosPri' => 450.00,
                'NCostPrice' => 450.00,
                'ExtraPrice' => 20.00,
                'WholePrice' => 430.00,
                'ReOrdlLvl' => 50,
                'ScallItem' => false,
                'SupKey' => 1, // Assuming supplier reference
                'RtQty1' => 5,
                'RtDis1' => 5.00,
                'RtQty2' => 10,
                'RtDis2' => 7.50,
                'RtQty3' => 20,
                'RtDis3' => 10.00,
                'RtQty4' => 50,
                'RtDis4' => 15.00,
                'WSQty1' => 100,
                'WSDis1' => 12.00,
                'WSQty2' => 200,
                'WSDis2' => 15.00,
                'WSQty3' => 500,
                'WSDis3' => 18.00,
                'WSQty4' => 1000,
                'WSDis4' => 20.00,
                'DiscountQty' => 2,
                'QuntityDiscount' => 3.00,
                'CCPrice' => 500.00,
                'SlsPri' => 500.00,
                'MaxOrdQty' => 1000,
                'ExpiryDate' => '2024-12-31',
                'Qty2' => null,
                'WithDates' => true,
                'ProductionDate' => '2023-01-15',
                'BatchNo' => 'BATCH001',
                'VATItem' => true,
                'DoProcess' => false,
                'DoRound' => false,
                'ProcessRatio' => null,
                'OrderNo' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fInAct' => false,
                'ItmCd' => 'ITM002',
                'Status' => 'Active',
                'CKey' => 2,
                'ItemCode' => 'P002',
                'BarCode' => '8901234567891',
                'ItmNm' => 'Wheat Flour 1kg',
                'EnglishName' => 'Wheat Flour 1kg',
                'catkey' => 'CAT001',
                'ItmRefKy' => null,
                'UnitKy' => 1,
                'CosPri' => 85.00,
                'NCostPrice' => 85.00,
                'ExtraPrice' => 5.00,
                'WholePrice' => 80.00,
                'ReOrdlLvl' => 100,
                'ScallItem' => false,
                'SupKey' => 1,
                'RtQty1' => 10,
                'RtDis1' => 3.00,
                'RtQty2' => 25,
                'RtDis2' => 5.00,
                'RtQty3' => 50,
                'RtDis3' => 7.00,
                'RtQty4' => 100,
                'RtDis4' => 10.00,
                'WSQty1' => 200,
                'WSDis1' => 12.00,
                'WSQty2' => 500,
                'WSDis2' => 15.00,
                'WSQty3' => 1000,
                'WSDis3' => 18.00,
                'WSQty4' => 2000,
                'WSDis4' => 20.00,
                'DiscountQty' => 5,
                'QuntityDiscount' => 2.00,
                'CCPrice' => 95.00,
                'SlsPri' => 95.00,
                'MaxOrdQty' => 2000,
                'ExpiryDate' => '2024-06-30',
                'Qty2' => null,
                'WithDates' => true,
                'ProductionDate' => '2023-02-20',
                'BatchNo' => 'BATCH002',
                'VATItem' => true,
                'DoProcess' => false,
                'DoRound' => false,
                'ProcessRatio' => null,
                'OrderNo' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fInAct' => false,
                'ItmCd' => 'ITM003',
                'Status' => 'Active',
                'CKey' => 3,
                'ItemCode' => 'P003',
                'BarCode' => '8901234567892',
                'ItmNm' => 'Sugar 1kg',
                'EnglishName' => 'Sugar 1kg',
                'catkey' => 'CAT002',
                'ItmRefKy' => null,
                'UnitKy' => 1,
                'CosPri' => 120.00,
                'NCostPrice' => 120.00,
                'ExtraPrice' => 10.00,
                'WholePrice' => 110.00,
                'ReOrdlLvl' => 80,
                'ScallItem' => true,
                'SupKey' => 2,
                'RtQty1' => 5,
                'RtDis1' => 2.00,
                'RtQty2' => 10,
                'RtDis2' => 4.00,
                'RtQty3' => 20,
                'RtDis3' => 6.00,
                'RtQty4' => 50,
                'RtDis4' => 8.00,
                'WSQty1' => 100,
                'WSDis1' => 10.00,
                'WSQty2' => 250,
                'WSDis2' => 12.00,
                'WSQty3' => 500,
                'WSDis3' => 15.00,
                'WSQty4' => 1000,
                'WSDis4' => 18.00,
                'DiscountQty' => 3,
                'QuntityDiscount' => 1.50,
                'CCPrice' => 130.00,
                'SlsPri' => 130.00,
                'MaxOrdQty' => 1500,
                'ExpiryDate' => '2025-03-15',
                'Qty2' => null,
                'WithDates' => true,
                'ProductionDate' => '2023-03-10',
                'BatchNo' => 'BATCH003',
                'VATItem' => true,
                'DoProcess' => false,
                'DoRound' => false,
                'ProcessRatio' => null,
                'OrderNo' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fInAct' => true,
                'ItmCd' => 'ITM004',
                'Status' => 'Inactive',
                'CKey' => 4,
                'ItemCode' => 'P004',
                'BarCode' => '8901234567893',
                'ItmNm' => 'Discontinued Product',
                'EnglishName' => 'Discontinued Product',
                'catkey' => 'CAT003',
                'ItmRefKy' => null,
                'UnitKy' => 1,
                'CosPri' => 200.00,
                'NCostPrice' => 200.00,
                'ExtraPrice' => 0.00,
                'WholePrice' => 180.00,
                'ReOrdlLvl' => 0,
                'ScallItem' => false,
                'SupKey' => 3,
                'RtQty1' => null,
                'RtDis1' => null,
                'RtQty2' => null,
                'RtDis2' => null,
                'RtQty3' => null,
                'RtDis3' => null,
                'RtQty4' => null,
                'RtDis4' => null,
                'WSQty1' => null,
                'WSDis1' => null,
                'WSQty2' => null,
                'WSDis2' => null,
                'WSQty3' => null,
                'WSDis3' => null,
                'WSQty4' => null,
                'WSDis4' => null,
                'DiscountQty' => null,
                'QuntityDiscount' => null,
                'CCPrice' => 220.00,
                'SlsPri' => 220.00,
                'MaxOrdQty' => 0,
                'ExpiryDate' => '2023-12-31',
                'Qty2' => null,
                'WithDates' => false,
                'ProductionDate' => null,
                'BatchNo' => null,
                'VATItem' => false,
                'DoProcess' => false,
                'DoRound' => false,
                'ProcessRatio' => null,
                'OrderNo' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'fInAct' => false,
                'ItmCd' => 'ITM005',
                'Status' => 'Active',
                'CKey' => 5,
                'ItemCode' => 'P005',
                'BarCode' => '8901234567894',
                'ItmNm' => 'Milk Powder 400g',
                'EnglishName' => 'Milk Powder 400g',
                'catkey' => 'CAT004',
                'ItmRefKy' => null,
                'UnitKy' => 1,
                'CosPri' => 350.00,
                'NCostPrice' => 350.00,
                'ExtraPrice' => 25.00,
                'WholePrice' => 330.00,
                'ReOrdlLvl' => 60,
                'ScallItem' => false,
                'SupKey' => 4,
                'RtQty1' => 3,
                'RtDis1' => 4.00,
                'RtQty2' => 6,
                'RtDis2' => 6.00,
                'RtQty3' => 12,
                'RtDis3' => 8.00,
                'RtQty4' => 24,
                'RtDis4' => 10.00,
                'WSQty1' => 50,
                'WSDis1' => 12.00,
                'WSQty2' => 100,
                'WSDis2' => 15.00,
                'WSQty3' => 200,
                'WSDis3' => 18.00,
                'WSQty4' => 500,
                'WSDis4' => 20.00,
                'DiscountQty' => 2,
                'QuntityDiscount' => 2.50,
                'CCPrice' => 380.00,
                'SlsPri' => 380.00,
                'MaxOrdQty' => 500,
                'ExpiryDate' => '2024-08-15',
                'Qty2' => null,
                'WithDates' => true,
                'ProductionDate' => '2023-04-05',
                'BatchNo' => 'BATCH005',
                'VATItem' => true,
                'DoProcess' => false,
                'DoRound' => false,
                'ProcessRatio' => null,
                'OrderNo' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        // Insert data
        DB::table('itemmaster')->insert($items);

        $this->command->info('ItemMaster table seeded successfully with ' . count($items) . ' records.');
    }
}